### ISSUE TITLE
Error:Execution failed for task ':testapp:mergeDebugManifest'.

### ISSUE THREAD

**Issue by hnty545** [Vigi0303/fat-aar-plugin#10]
Error:Execution failed for task ':testapp:mergeDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: java.io.FileNotFoundException: D:\workspace_as\paysdk\PaySdk\testapp\build\intermediates\exploded-aar\PaySdk\MposDriverFrameworkBbposDriver\unspecified\AndroidManifest.xml (系统找不到指定的路径。)

android studio 2.3
com.android.tools.build:gradle:2.3.0
com.android.library
compileSdkVersion 25

**Comment by hnty545** [comment]
为啥关了呀。。

**Comment by vigidroid** [comment]
2.3.0不支持，换2.2.3
