### ISSUE TITLE
请问如何打出混淆的aar包

### ISSUE THREAD

**Issue by hnty545** [Vigi0303/fat-aar-plugin#11]
我引入了几个library，那几个库都需要混淆，我注意到使用您的插件打出了-debug包，内部的libs文件夹下有那些库的jar包，请问可以混淆那些jar吗，在各个库工程下可以设置吗

**Comment by vigidroid** [comment]
可以，开混淆就行了。参见readme有写的

**Comment by hnty545** [comment]
是所有module都开混淆，还是打包的module开混淆呢，readme没见有写呀
另外我试过打包的module开混淆，好像生成不了release的aar，只有debug的
是否要去执行buildRelease这个任务呢

**Comment by vigidroid** [comment]
建议去找android gradle构建系统的教程去学习一下

**Comment by hnty545** [comment]
是所有module都开混淆，还是打包的module开混淆呢
