### ISSUE TITLE
org.xml.sax.SAXParseException

### ISSUE THREAD

**Issue by hnty545** [Vigi0303/fat-aar-plugin#12]
Error while saving blame file, build will continue
org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 222; 与元素类型 "uses-sdk" 相关联的属性 "tools:overrideLibrary" 的前缀 "tools" 未绑定。
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)

android studio 2.3
com.android.tools.build:gradle:2.3.0

**Comment by hnty545** [comment]
我执行的是bundleRelease任务，虽然报以上的错，但是-release.jar还是生成了
但发现classes.jar只是本库的class文件，而依赖的库是在libs文件夹里，我打开了本工程的minifyEnabled true，但是那些库都没有被混淆
我把那些库的混淆打开以后，编译的时候就找不到类报错了

所以还是不知道得到混淆的aar

**Comment by hnty545** [comment]
我又运行了一次bundleRelease很惊喜classes.jar里是混淆的效果了，libs里没有文件了。
但是使用aar的时候也如下提示：
Error:Execution failed for task ':app:processDebugManifest'.
> com.android.manifmerger.ManifestMerger2$MergeFailureException: org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 222; 与元素类型 "uses-sdk" 相关联的属性 "tools:overrideLibrary" 的前缀 "tools" 未绑定。
与打包时的错误提示想对应，想请问这怎么解决呢？

**Comment by hnty545** [comment]
我发现是aar中的manifest文件里，uses-sdk标签下有tools:overrideLibrary，但是manifest里没有声明tools，请问这是打包的问题吗，是否是插件的bug呢？

**Comment by hnty545** [comment]
另外，我是一个app工程改成library后来执行打包的，因为这个app工程引用的模块比较全，这样做比较方便。
我在aar中的manifest文件里加上tools声明以后，使用aar时就没有报错了

**Comment by hnty545** [comment]
使用的时候启动找不到R文件
 java.lang.NoClassDefFoundError: com.XXX.ui.R$style

**Comment by hnty545** [comment]
当引入多个模块，有不同R资源的时候，只有打包aar的那个工程R类可以访问，其他模块的R访问不到

**Comment by hnty545** [comment]
我看到其实各个模块的资源id都汇总到R文件里了
使用aar生成的R是根据manifest的package来觉得生成什么路径的R
但是各个模块里的代码使用的R又是不同路径的
这样除了打包工程的manifest声明的package下的R能正常使用，其他模块的R都找不到了
请问有办法让使用aar的工程分别生成不同路径的R文件吗

**Comment by vigidroid** [comment]
如果想观察了解实现细节，建议跑一下[example](https://github.com/Vigi0303/fat-aar-plugin/tree/hack-into/example-android)
