### ISSUE TITLE
"joor" not found

### ISSUE THREAD

**Issue by lazerwalker** [Vigi0303/fat-aar-plugin#19]
I'm running into this error when trying to set this up:

<img width="779" alt="screen shot 2018-02-14 at 11 19 43 pm" src="https://user-images.githubusercontent.com/821238/36231260-b14ec2e6-11dd-11e8-973b-2247650f0057.png">

I'm using Gradle 3.0.1, which I suspect will later fail for other reasons, but probably isn't relevant to this particular error

Anyone else run into this and/or have a fix?

**Comment by JustinTullgren** [comment]
I just ran into this as well.  Add maven central.
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            url  "http://dl.bintray.com/vigidroid/maven"
        }
    }
    dependencies {
        classpath 'me.vigi:fat-aar-plugin:0.2.8'
    }
}
```

**Comment by vigidroid** [comment]
joor is available in jcenter.
see https://jcenter.bintray.com/org/jooq/joor/0.9.6/
