### ISSUE TITLE
兄弟，请教一个问题？

### ISSUE THREAD

**Issue by Ficat** [Vigi0303/fat-aar-plugin#25]
用fat-aar打包时，依赖的是一个aar，但是打不进去，报找不到R文件下一些资源符号的错误（查了下是找不到support：appcompatv7下的一些资源）。请问这个问题何解？
![image](https://user-images.githubusercontent.com/30248537/46645948-f08d9900-cbb9-11e8-88f1-d4e20c0d008e.png)

**Comment by vigidroid** [comment]
我刚试了下没问题。
看你这报错是找不到support包内的资源文件，检查一下你是否引用了support包
