### ISSUE TITLE
fat-aar includes release libs in its debug assembled aar output

### ISSUE THREAD

**Issue by minkyn** [Vigi0303/fat-aar-plugin#7]
My project is setup as follows:
```
root
|----build/
|----module_a
|    |----build/
|    |----build.gradle
|    |----proguard.pro
|----module_b
|    |----build/
|    |----build.gradle
|    |----proguard.pro
|----build.gradle
```

In the `build.gradle` of both `module_a` and `module_b`, I applied
```
android {
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
```

And in their respective `build/` directory I can see that `release.aar` is obfuscated while `debug.aar` is not.

Then in the top level `build.gradle` of `root`, I did
```
apply plugin: 'me.vigi.fat-aar'

dependencies {
    embed (project(':module_a')) {
        transitive false
    }
    embed (project(':module_b')) {
        transitive false
    }
}
```

But in its own `build/` directory, I find that both `release.aar` and `debug.aar` contains jar libs from `module_a` and `module_b` as obfuscated.

Please help fix this issue. Thanks!

**Comment by vigidroid** [comment]
> By default a library only publishes its `release` variant.

See [here](http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Library-Publication).
